name: 'Close stale issues and PRs'

on:
  schedule:
    - cron: '30 1 1 1 *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'trigger issue autoclose manually'  

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          stale-issue-message: ''
          stale-pr-message: ''
          operations-per-run: 30
          days-before-close: 0
          days-before-stale: 60

